version: '3'
services:
  x11:
    image: bilbaogoyoaga/x11
    build:
      context: ../util/
      dockerfile: Dockerfile_x11

    container_name: x11

  atom_node:
    image: bilbaogoyoaga/atom_node
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - usuario=atom

    container_name: atom_node

    environment:
      - DISPLAY=${DISPLAY:-":0.0"}

    network_mode: "host"
    restart: "no"
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /dev/shm:/dev/shm
      - /trabajos:/trabajos
    working_dir: /trabajos
    command: bash -c "/usr/bin/atom -f /home/cris/sereda"
