version: '3'
services:
  jdk8_x11:
    image: bilbaogoyoaga/x11_jdk8
    build:
      context: ../util/
      dockerfile: Dockerfile_x11_jdk8

    container_name: x11_jdk8

  eclipse:
    image: bilbaogoyoaga/eclipse-photon
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - usuario=cris

    container_name: eclipse-photon

    environment:
      - DISPLAY=${DISPLAY:-":0.0"}

    network_mode: "host"
    restart: "no"
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /dev/shm:/dev/shm
      - /trabajos:/trabajos
    working_dir: /trabajos
    command: /opt/eclipse/eclipse
