version: '3'
services:
  x11:
    build:
      context: ./
      dockerfile: Dockerfile_x11
      args:
        - usuario=cris

    container_name: x11

    environment:
      - DISPLAY=${DISPLAY}

  atom:
    build:
      context: ./
      dockerfile: Dockerfile_atom
      args:
        - usuario=cris

    container_name: atom

    environment:
      - DISPLAY=${DISPLAY}

    network_mode: "host"
    restart: "no"
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /dev/shm:/dev/shm
      - /trabajos:/trabajos
    working_dir: /trabajos
    command: bash -c "/usr/bin/atom -f /trabajos/mintuatze/mintuatze-app"
