version: '3'
services:
  x11:
    image: bilbaogoyoaga/x11
    build:
      context: ../x11/
      dockerfile: Dockerfile

    container_name: x11

  atom:
    image: bilbaogoyoaga/atom
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - usuario=cris

    container_name: atom

    environment:
      - DISPLAY=${DISPLAY:-":0.0"}

    network_mode: "host"
    restart: "no"
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /dev/shm:/dev/shm
      - /trabajos:/trabajos
    working_dir: /trabajos
    command: bash -c "/usr/bin/atom -f /trabajos/mintuatze/mintuatze-app"
