version: '3'
services:
  node:
    image: bilbaogoyoaga/node
    build:
      context: ../node
      dockerfile: Dockerfile

    container_name: node
    network_mode: "host"
    restart: "no"
    volumes:
      - /trabajos:/trabajos
    working_dir: /trabajos
    stdin_open: true
    tty: true

  atom:
    image: bilbaogoyoaga/atom
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - usuario=atom

    container_name: atom

    environment:
      - DISPLAY=${DISPLAY:-":0.0"}

    network_mode: "host"
    restart: "no"
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /dev/shm:/dev/shm
      - /trabajos:/trabajos
    working_dir: /trabajos
    command: bash -c "/usr/bin/atom -f /trabajos/mintuatze/mintuatze-app"
